id: I65553EED
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T11:42:04+00:00'
last_modified: '2022-06-07T21:30:57.562495+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29014
  title: དུས་རབས་ཀྱི་བསམ་གཞིགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    E7D8:
      image_group_id: I5021
      title: ''
      total_pages: 262
      order: 1
      base_file: E7D8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
