id: P004263
initial_creation_type: ocr
source_metadata:
  id: bdr:W29014
  title: དུས་རབས་ཀྱི་བསམ་གཞིགས
  author: ''
  volumes:
    36cd8623d3564849872ebf1a8963d6dd:
      image_group_id: I5021
      title: ''
      volume_number: 1
      total_pages: 262
